export const PROJECT_REMARK = " Built from Piper, By Adam - The Developer ";

export const SQL_NULL_LITERAL = "NULL";
export const MONGO_NULL_LITERAL = "null";

export const EXPORT_BANNER = {
  postgres: "-- PostgreSQL dump generated by dump-generator",
  mysql: "-- MySQL dump generated by dump-generator",
  sqlite: "-- SQLite dump generated by dump-generator",
  mongo: "// MongoDB dump generated by dump-generator",
} as const;
