import type { Field } from "@/src/core/schema/schema.model";

export type EntityTemplate = {
  /** Primary table name for the first occurrence of this shape. */
  name: string;
  /** Additional realistic table names for repeated uses of the same template (same column layout). */
  alternateTableNames: string[];
  fields: Field[];
};

export const ENTITY_TEMPLATES: EntityTemplate[] = [
  {
    name: "users",
    alternateTableNames: [
      "user_profiles",
      "user_preferences",
      "user_security_settings",
      "user_api_keys",
      "user_devices",
      "user_consents",
      "user_invitations",
      "user_activity_log",
      "user_segments",
      "service_accounts",
      "user_mfa_factors",
      "user_login_history",
    ],
    fields: [
      { name: "id", type: "uuid", nullable: false },
      { name: "email", type: "string", nullable: false },
      { name: "first_name", type: "string", nullable: false },
      { name: "last_name", type: "string", nullable: false },
      { name: "phone", type: "string", nullable: true },
      { name: "timezone", type: "string", nullable: true },
      { name: "locale", type: "string", nullable: true },
      { name: "is_active", type: "boolean", nullable: false },
      { name: "email_verified_at", type: "timestamp", nullable: true },
      { name: "last_login_at", type: "timestamp", nullable: true },
      { name: "created_at", type: "timestamp", nullable: false },
      { name: "updated_at", type: "timestamp", nullable: true },
    ],
  },
  {
    name: "organizations",
    alternateTableNames: [
      "organization_units",
      "organization_domains",
      "organization_branding",
      "organization_billing_profiles",
      "organization_teams",
      "organization_roles",
      "organization_audit_log",
      "partner_accounts",
      "tenant_settings",
      "company_registrations",
      "org_feature_flags",
      "org_entitlements",
    ],
    fields: [
      { name: "id", type: "uuid", nullable: false },
      { name: "name", type: "string", nullable: false },
      { name: "legal_name", type: "string", nullable: true },
      { name: "industry", type: "string", nullable: true },
      { name: "country", type: "string", nullable: false },
      { name: "region", type: "string", nullable: true },
      { name: "employee_count_band", type: "string", nullable: true },
      { name: "website_url", type: "string", nullable: true },
      { name: "created_at", type: "timestamp", nullable: false },
      { name: "updated_at", type: "timestamp", nullable: true },
    ],
  },
  {
    name: "products",
    alternateTableNames: [
      "product_variants",
      "product_inventory",
      "product_media",
      "product_tags",
      "product_pricing_rules",
      "bundled_products",
      "digital_goods",
      "product_suppliers",
      "stock_reservations",
      "product_translations",
      "sku_aliases",
      "product_compliance",
    ],
    fields: [
      { name: "id", type: "uuid", nullable: false },
      { name: "sku", type: "string", nullable: false },
      { name: "name", type: "string", nullable: false },
      { name: "slug", type: "string", nullable: true },
      { name: "description", type: "text", nullable: true },
      { name: "unit_price", type: "decimal", nullable: false },
      { name: "cost_price", type: "decimal", nullable: true },
      { name: "tax_code", type: "string", nullable: true },
      { name: "is_active", type: "boolean", nullable: false },
      { name: "published_at", type: "timestamp", nullable: true },
      { name: "created_at", type: "timestamp", nullable: false },
      { name: "updated_at", type: "timestamp", nullable: true },
    ],
  },
  {
    name: "orders",
    alternateTableNames: [
      "order_status_history",
      "order_notes",
      "order_shipments",
      "order_discounts",
      "cart_checkouts",
      "purchase_orders",
      "wholesale_orders",
      "order_returns",
      "order_fulfillment_tasks",
      "order_risk_assessments",
      "guest_checkouts",
      "subscription_orders",
    ],
    fields: [
      { name: "id", type: "uuid", nullable: false },
      { name: "order_number", type: "string", nullable: false },
      {
        name: "status",
        type: "enum",
        nullable: false,
        enumValues: ["pending", "paid", "shipped", "cancelled"],
      },
      { name: "currency", type: "string", nullable: false },
      { name: "subtotal_amount", type: "decimal", nullable: false },
      { name: "tax_amount", type: "decimal", nullable: true },
      { name: "shipping_amount", type: "decimal", nullable: true },
      { name: "total_amount", type: "decimal", nullable: false },
      { name: "customer_notes", type: "text", nullable: true },
      { name: "placed_at", type: "timestamp", nullable: false },
      { name: "fulfilled_at", type: "timestamp", nullable: true },
    ],
  },
  {
    name: "order_items",
    alternateTableNames: [
      "line_item_adjustments",
      "cart_line_items",
      "quote_line_items",
      "rma_line_items",
      "gift_line_items",
      "subscription_line_items",
      "bundle_line_components",
      "dropship_line_items",
      "preorder_line_items",
      "exchange_line_items",
      "tax_line_allocations",
      "loyalty_redemptions",
    ],
    fields: [
      { name: "id", type: "uuid", nullable: false },
      { name: "quantity", type: "int", nullable: false },
      { name: "unit_price", type: "decimal", nullable: false },
      { name: "discount_amount", type: "decimal", nullable: true },
      { name: "tax_amount", type: "decimal", nullable: true },
      { name: "line_total", type: "decimal", nullable: false },
      { name: "sku_snapshot", type: "string", nullable: true },
      { name: "fulfillment_status", type: "string", nullable: true },
    ],
  },
  {
    name: "payments",
    alternateTableNames: [
      "payment_methods",
      "payment_intents",
      "refund_requests",
      "chargebacks",
      "payout_batches",
      "ledger_entries",
      "wallet_transactions",
      "gift_card_redemptions",
      "bank_transfers",
      "payment_disputes",
      "installment_plans",
      "credit_memos",
    ],
    fields: [
      { name: "id", type: "uuid", nullable: false },
      { name: "provider", type: "string", nullable: false },
      { name: "provider_reference", type: "string", nullable: true },
      {
        name: "status",
        type: "enum",
        nullable: false,
        enumValues: ["initiated", "authorized", "captured", "failed"],
      },
      { name: "amount", type: "decimal", nullable: false },
      { name: "fee_amount", type: "decimal", nullable: true },
      { name: "currency", type: "string", nullable: false },
      { name: "failure_code", type: "string", nullable: true },
      { name: "processed_at", type: "timestamp", nullable: true },
      { name: "created_at", type: "timestamp", nullable: false },
    ],
  },
  {
    name: "addresses",
    alternateTableNames: [
      "shipping_locations",
      "billing_addresses",
      "warehouse_addresses",
      "pickup_points",
      "return_addresses",
      "legal_addresses",
      "tax_nexus_addresses",
      "drop_ship_origins",
      "customer_locations",
      "vendor_addresses",
      "fulfillment_centers",
      "mailing_list_addresses",
    ],
    fields: [
      { name: "id", type: "uuid", nullable: false },
      { name: "label", type: "string", nullable: true },
      { name: "line1", type: "string", nullable: false },
      { name: "line2", type: "string", nullable: true },
      { name: "city", type: "string", nullable: false },
      { name: "state", type: "string", nullable: true },
      { name: "postal_code", type: "string", nullable: false },
      { name: "country", type: "string", nullable: false },
      { name: "latitude", type: "decimal", nullable: true },
      { name: "longitude", type: "decimal", nullable: true },
      { name: "validated_at", type: "timestamp", nullable: true },
    ],
  },
  {
    name: "subscriptions",
    alternateTableNames: [
      "subscription_items",
      "subscription_discounts",
      "subscription_schedules",
      "usage_records",
      "seat_allocations",
      "trial_extensions",
      "billing_cycles",
      "plan_migrations",
      "contract_terms",
      "renewal_reminders",
      "dunning_events",
      "metered_balances",
    ],
    fields: [
      { name: "id", type: "uuid", nullable: false },
      { name: "plan_code", type: "string", nullable: false },
      {
        name: "status",
        type: "enum",
        nullable: false,
        enumValues: ["trialing", "active", "past_due", "cancelled"],
      },
      { name: "billing_interval", type: "string", nullable: false },
      { name: "quantity", type: "int", nullable: true },
      { name: "started_at", type: "timestamp", nullable: false },
      { name: "current_period_end", type: "timestamp", nullable: true },
      { name: "cancel_at", type: "timestamp", nullable: true },
      { name: "ended_at", type: "timestamp", nullable: true },
    ],
  },
  {
    name: "invoices",
    alternateTableNames: [
      "invoice_line_items",
      "credit_notes",
      "proforma_invoices",
      "tax_documents",
      "remittance_advices",
      "billing_contacts",
      "payment_reminders",
      "collection_cases",
      "write_offs",
      "invoice_sequences",
      "accrual_snapshots",
      "vat_registrations",
    ],
    fields: [
      { name: "id", type: "uuid", nullable: false },
      { name: "invoice_number", type: "string", nullable: false },
      { name: "subtotal", type: "decimal", nullable: false },
      { name: "tax_amount", type: "decimal", nullable: false },
      { name: "total_amount", type: "decimal", nullable: false },
      { name: "currency", type: "string", nullable: false },
      { name: "due_at", type: "timestamp", nullable: true },
      { name: "paid_at", type: "timestamp", nullable: true },
      { name: "issued_at", type: "timestamp", nullable: false },
    ],
  },
  {
    name: "sessions",
    alternateTableNames: [
      "refresh_tokens",
      "device_sessions",
      "oauth_states",
      "login_attempts",
      "trusted_devices",
      "session_revocations",
      "api_session_keys",
      "mobile_sessions",
      "webauthn_credentials",
      "impersonation_sessions",
      "sso_bindings",
      "idle_timeouts",
    ],
    fields: [
      { name: "id", type: "uuid", nullable: false },
      { name: "ip_address", type: "string", nullable: false },
      { name: "user_agent", type: "text", nullable: false },
      { name: "country_code", type: "string", nullable: true },
      { name: "is_trusted", type: "boolean", nullable: false },
      { name: "expires_at", type: "timestamp", nullable: false },
      { name: "last_seen_at", type: "timestamp", nullable: true },
      { name: "created_at", type: "timestamp", nullable: false },
    ],
  },
  {
    name: "events",
    alternateTableNames: [
      "audit_events",
      "webhook_deliveries",
      "integration_events",
      "domain_events_outbox",
      "analytics_events",
      "security_events",
      "feature_usage_events",
      "email_events",
      "billing_events",
      "search_events",
      "experiment_exposures",
      "cdc_change_events",
    ],
    fields: [
      { name: "id", type: "uuid", nullable: false },
      { name: "event_type", type: "string", nullable: false },
      { name: "source", type: "string", nullable: false },
      { name: "correlation_id", type: "string", nullable: true },
      { name: "payload", type: "json", nullable: false },
      { name: "schema_version", type: "string", nullable: true },
      { name: "occurred_at", type: "timestamp", nullable: false },
      { name: "ingested_at", type: "timestamp", nullable: true },
    ],
  },
  {
    name: "notifications",
    alternateTableNames: [
      "notification_reads",
      "notification_preferences",
      "push_notification_tokens",
      "notification_delivery_log",
      "in_app_message_inbox",
      "notification_digest_queue",
      "notification_suppressions",
      "notification_templates",
      "broadcast_notifications",
      "notification_webhooks",
      "notification_channels",
      "sms_opt_outs",
    ],
    fields: [
      { name: "id", type: "uuid", nullable: false },
      {
        name: "channel",
        type: "enum",
        nullable: false,
        enumValues: ["email", "sms", "push"],
      },
      { name: "priority", type: "string", nullable: true },
      { name: "subject", type: "string", nullable: false },
      { name: "body", type: "text", nullable: false },
      { name: "template_key", type: "string", nullable: true },
      { name: "locale", type: "string", nullable: true },
      { name: "read_at", type: "timestamp", nullable: true },
      { name: "failed_reason", type: "text", nullable: true },
      { name: "external_reference", type: "string", nullable: true },
      { name: "sent_at", type: "timestamp", nullable: true },
      { name: "created_at", type: "timestamp", nullable: false },
    ],
  },
];