import type { DataSet } from "@/src/core/data/data.model";
import type { FieldType, Schema } from "@/src/core/schema/schema.model";
import type { DialectExporter } from "@/src/exporters/exporter.types";

function mapType(fieldType: FieldType): string {
  switch (fieldType) {
    case "uuid":
      return "CHAR(36)";
    case "int":
      return "INT";
    case "bigint":
      return "BIGINT";
    case "float":
      return "FLOAT";
    case "decimal":
      return "DECIMAL(18,4)";
    case "boolean":
      return "BOOLEAN";
    case "text":
      return "TEXT";
    case "date":
      return "DATE";
    case "timestamp":
      return "DATETIME";
    case "json":
      return "JSON";
    case "enum":
      return "VARCHAR(64)";
    case "string":
    default:
      return "VARCHAR(255)";
  }
}

function quote(value: unknown): string {
  if (value === null || value === undefined) {
    return "NULL";
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (typeof value === "object") {
    return `'${JSON.stringify(value).replaceAll("'", "''")}'`;
  }
  return `'${String(value).replaceAll("'", "''")}'`;
}

export class MysqlExporter implements DialectExporter {
  export(schema: Schema, data: DataSet): string {
    const stmts: string[] = ["-- MySQL dump generated by dump-generator"];

    for (const entity of schema.entities) {
      const columns = entity.fields.map((field) => {
        const nullable = field.nullable ? "" : " NOT NULL";
        return `  \`${field.name}\` ${mapType(field.type)}${nullable}`;
      });
      columns.push(
        `  PRIMARY KEY (${entity.primaryKey.map((key) => `\`${key}\``).join(", ")})`,
      );
      stmts.push(`CREATE TABLE \`${entity.name}\` (\n${columns.join(",\n")}\n);`);
    }

    for (const entity of schema.entities) {
      const rows = data[entity.name] ?? [];
      for (const row of rows) {
        const columns = Object.keys(row).map((name) => `\`${name}\``);
        const values = Object.values(row).map((value) => quote(value));
        stmts.push(
          `INSERT INTO \`${entity.name}\` (${columns.join(", ")}) VALUES (${values.join(", ")});`,
        );
      }
    }

    return `${stmts.join("\n\n")}\n`;
  }
}
