import type { DataSet } from "@/src/core/data/data.model";
import type { FieldType, Schema } from "@/src/core/schema/schema.model";
import type { DialectExporter } from "@/src/exporters/exporter.types";

function mapType(fieldType: FieldType): string {
  switch (fieldType) {
    case "int":
    case "bigint":
      return "INTEGER";
    case "float":
    case "decimal":
      return "REAL";
    case "boolean":
      return "INTEGER";
    case "json":
    case "text":
    case "string":
    case "enum":
    case "uuid":
    case "date":
    case "timestamp":
    default:
      return "TEXT";
  }
}

function quote(value: unknown): string {
  if (value === null || value === undefined) {
    return "NULL";
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (typeof value === "object") {
    return `'${JSON.stringify(value).replaceAll("'", "''")}'`;
  }
  return `'${String(value).replaceAll("'", "''")}'`;
}

export class SqliteExporter implements DialectExporter {
  export(schema: Schema, data: DataSet): string {
    const stmts: string[] = ["-- SQLite dump generated by dump-generator"];

    for (const entity of schema.entities) {
      const columns = entity.fields.map((field) => {
        const nullable = field.nullable ? "" : " NOT NULL";
        return `  "${field.name}" ${mapType(field.type)}${nullable}`;
      });
      columns.push(
        `  PRIMARY KEY (${entity.primaryKey.map((key) => `"${key}"`).join(", ")})`,
      );
      stmts.push(`CREATE TABLE "${entity.name}" (\n${columns.join(",\n")}\n);`);
    }

    for (const entity of schema.entities) {
      const rows = data[entity.name] ?? [];
      for (const row of rows) {
        const columns = Object.keys(row).map((name) => `"${name}"`);
        const values = Object.values(row).map((value) => quote(value));
        stmts.push(
          `INSERT INTO "${entity.name}" (${columns.join(", ")}) VALUES (${values.join(", ")});`,
        );
      }
    }

    return `${stmts.join("\n\n")}\n`;
  }
}
